In [1]:
%matplotlib inline
import numpy as np


/Users/gditzler/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [8]:
u = np.array([1.,2.,3.])
v = np.array([4.,5.,6.])
print u*v
print np.dot(u, v)
print np.outer(u, v)

[  4.  10.  18.]
32.0
[[  4.   5.   6.]
 [  8.  10.  12.]
 [ 12.  15.  18.]]


In [13]:
C = np.random.randn(5, 5)
print np.linalg.det(C)
print np.trace(C)

-4.56892601558
1.6137798688


In [15]:
w, v = np.linalg.eig(np.diag((1, 2, 3)))
print v, u

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] [ 1.  2.  3.]
